"""
GIVE BASICALLY ALL OF THESE ACTUAL VALUES CORRESPONDING TO THE PROPER PORTS; CHECK GITHUB FOR PREVIOUS JAVA VERSION IF NEEDED
"""


#Driver controller constants
MAIN_JOYDRIVER_USB_PORT = 0

#Drivesystem constants
DRIVETRAIN_LEFT_FRONT = 0
DRIVETRAIN_LEFT_BACK = 0
DRIVETRAIN_RIGHT_FRONT = 0
DRIVETRAIN_RIGHT_BACK = 0

#Shouldersystem constants
ENCODER_SHOULDER_A = 0
ENCODER_SHOULDER_B = 0
SHOULDER_MOTOR_ONE = 0
SHOULDER_MOTOR_TWO = 0




